=head1 NAME

Ten.js - Light Weight JavaScript Framework

=head1 DESCRIPTION

Please see test html files under tests directory for detailed information.

=head1 AUTHORS

Junya Kondo, E<lt>http://d.hatena.ne.jp/jkondo/E<gt>

id:chris4403

In addition, following people contributed the project: id:secondlife,
id:nagayama, id:motemen, id:cho45, id:nanto_vi, and id:wakabatan.

=head1 COPYRIGHT AND LICENSE

Copyright (C) Hatena Inc. All Rights Reserved.

This library is free software; you may redistribute it and/or modify
it under the same terms as the Perl programming language.

=cut
